const MODELS = [
  {
    id: "claude-mythos",
    name: "Claude Mythos",
    vendor: "Anthropic",
    vendorColor: "purple",
    score: 99,
    pricePerM: 42.00,
    context: "200K",
    params: "未公开",
    region: "海外",
    tags: ["最强综合", "推理顶级", "编程", "多语言", "企业级"],
    strengths: { reasoning: 97, coding: 100, knowledge: 99, math: 90, multilingual: 100, multimodal: 98 },
    dataSource: "BenchLM (2026-05), 推理/数学为基于同类模型估算",
    releaseDate: "2026-02"
  },
  {
    id: "gemini-31-pro",
    name: "Gemini 3.1 Pro",
    vendor: "Google",
    vendorColor: "blue",
    score: 92,
    pricePerM: 10.50,
    context: "2000K",
    params: "未公开",
    region: "海外",
    tags: ["多模态王者", "超长文本", "多语言", "编程", "Agent"],
    strengths: { reasoning: 97, coding: 94, knowledge: 95, math: 67, multilingual: 100, multimodal: 84 },
    dataSource: "BenchLM (2026-05)",
    releaseDate: "2026-03"
  },
  {
    id: "qwen-37-max",
    name: "Qwen3.7 Max",
    vendor: "阿里",
    vendorColor: "amber",
    score: 92,
    pricePerM: 5.80,
    context: "1000K",
    params: "未公开",
    region: "国产",
    tags: ["中国最强", "国产开源", "中文", "编程", "Agent"],
    strengths: { reasoning: 96, coding: 92, knowledge: 87, math: 85, multilingual: 88, multimodal: 78 },
    dataSource: "BenchLM (2026-05), 数学/多模态为估算",
    releaseDate: "2026-05"
  },
  {
    id: "gpt-55",
    name: "GPT-5.5",
    vendor: "OpenAI",
    vendorColor: "green",
    score: 91,
    pricePerM: 42.00,
    context: "128K",
    params: "未公开",
    region: "海外",
    tags: ["生态最成熟", "知识面广", "数学", "推理", "编程"],
    strengths: { reasoning: 97, coding: 84, knowledge: 98, math: 97, multilingual: 92, multimodal: 57 },
    dataSource: "BenchLM (2026-05), ARC-AGI-2 85%, FrontierMath 51.7%",
    releaseDate: "2026-03"
  },
  {
    id: "claude-opus-47",
    name: "Claude Opus 4.7",
    vendor: "Anthropic",
    vendorColor: "purple",
    score: 90,
    pricePerM: 76.00,
    context: "200K",
    params: "未公开",
    region: "海外",
    tags: ["编程专精", "推理强者", "法律", "编程", "长文本"],
    strengths: { reasoning: 92, coding: 95, knowledge: 99, math: 75, multilingual: 90, multimodal: 48 },
    dataSource: "BenchLM (2026-05), SWE-Bench 80.8%·多语言为估算",
    releaseDate: "2025-12"
  },
  {
    id: "deepseek-v4-pro",
    name: "DeepSeek V4 Pro",
    vendor: "DeepSeek",
    vendorColor: "coral",
    score: 88,
    pricePerM: 3.48,
    context: "1000K",
    params: "1.6T MoE",
    region: "国产",
    tags: ["全球性价比王", "中文最强", "编程", "长文本", "国产开源"],
    strengths: { reasoning: 85, coding: 90, knowledge: 77, math: 80, multilingual: 88, multimodal: 65 },
    dataSource: "BenchLM (2026-05), 4个维度缺失为基于LLM Stats估算",
    releaseDate: "2026-05"
  },
  {
    id: "gemini-35-flash",
    name: "Gemini 3.5 Flash",
    vendor: "Google",
    vendorColor: "blue",
    score: 87,
    pricePerM: 0.65,
    context: "1000K",
    params: "未公开",
    region: "海外",
    tags: ["极速推理", "Agent王者", "Agent", "多模态", "批量处理"],
    strengths: { reasoning: 81, coding: 78, knowledge: 84, math: 70, multilingual: 80, multimodal: 81 },
    dataSource: "BenchLM (2026-05), 数学/多语言为估算",
    releaseDate: "2026-05"
  },
  {
    id: "kimi-k26",
    name: "Kimi K2.6",
    vendor: "Moonshot",
    vendorColor: "pink",
    score: 85,
    pricePerM: 5.20,
    context: "500K",
    params: "未公开",
    region: "国产",
    tags: ["中文写作", "K2.6升级", "中文写作", "摘要", "翻译"],
    strengths: { reasoning: 82, coding: 89, knowledge: 76, math: 75, multilingual: 85, multimodal: 72 },
    dataSource: "BenchLM (2026-05), 3个维度为估算",
    releaseDate: "2026-04"
  },
  {
    id: "llama-4-maverick",
    name: "Llama 4 Maverick",
    vendor: "Meta",
    vendorColor: "gray",
    score: 82,
    pricePerM: 0.60,
    context: "128K",
    params: "400B MoE",
    region: "海外",
    tags: ["开源标杆", "低成本", "开源", "研究", "微调"],
    strengths: { reasoning: 78, coding: 80, knowledge: 80, math: 77, multilingual: 72, multimodal: 72 },
    dataSource: "LLM Stats + 公开评测 (2026-05)",
    releaseDate: "2025-07"
  },
  {
    id: "doubao-pro",
    name: "豆包 Pro",
    vendor: "字节",
    vendorColor: "teal",
    score: 80,
    pricePerM: 2.00,
    context: "128K",
    params: "未公开",
    region: "国产",
    tags: ["国产低价", "中文日常", "中文", "聊天", "创作"],
    strengths: { reasoning: 72, coding: 70, knowledge: 75, math: 65, multilingual: 82, multimodal: 68 },
    dataSource: "公开评测估算 (2026-05)",
    releaseDate: "2026-01"
  }
];
